
services:
  # MySQL/MariaDB 데이터베이스를 실행하는 컨테이너를 설정
  db:
    container_name: db
    #image: mysql:5.7        # 윈도우
    image: mysql:8.0 # 맥북
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: mysql
    expose:
      - 3306
    ports:
      - "3307:3306"
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/mysql

  # Django 개발 서버를 실행하고, 데이터베이스와 연결하는 컨테이너를 설정
  web:
    container_name: web
    # 현재 디렉토리에서 Dockerfile을 사용하여 이미지를 빌드
    build: .
    # 컨테이너가 시작될 때 실행할 명령어
    command: sh -c "python manage.py migrate --settings=KKaebi.settings.dev && python manage.py runserver 0.0.0.0:8000 --settings=KKaebi.settings.dev"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      DATABASE_NAME: mysql
      DATABASE_USER: root
      DATABASE_PASSWORD: mysql
      DATABASE_PORT: 3306
      DATABASE_HOST: db
      DJANGO_SETTINGS_MODULE: KKaebi.settings.dev
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on: # db 서비스에 의존성 - 데이터베이스 준비된 후에 시작
      - db

volumes:
  app:
  dbdata:
