services:
  db:
    container_name: db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-pmysql"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    container_name: web
    build: .
    command: sh -c "python manage.py migrate --settings=${DJANGO_SETTINGS_MODULE} && python manage.py runserver 0.0.0.0:8000 --settings=${DJANGO_SETTINGS_MODULE}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_HOST: ${DATABASE_HOST}
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  dbdata:


nginx:
  container_name: nginx
  build: ./config/nginx
  depends_on:
    - web