name: Deploy to EC2

on:
  push:
    branches:
      - main # main 브랜치에 push되었을 때
  pull_request:
    branches:
      - main # main 브랜치에 PR 날렸을 때

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # GitHub 리포지토리 체크아웃
      - name: checkout
        uses: actions/checkout@v3

      # Action Secret에 설정한 ENV_VARS 값을 .env 파일로 생성
      - name: create env file
        run: |
          touch .env
          echo "${{ secrets.ENV_VARS }}" >> .env

      # EC2에 접속해 원격 디렉토리 생성
      - name: create remote directory
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: mkdir -p /home/ubuntu/srv/ubuntu

      # SSH 키를 통해 소스 코드를 EC2 인스턴스로 복사
      - name: copy source via ssh key
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          remote_path: /home/ubuntu/srv/ubuntu/
          remote_host: ${{ secrets.HOST }}
          remote_user: ubuntu
          remote_key: ${{ secrets.KEY }}

      # 서버에 접속한 뒤 deploy.sh 실행
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            sh /home/ubuntu/srv/ubuntu/config/scripts/deploy.sh
