name: Deploy to EC2

# on의 이벤트가 발생하면 jobs 실행
# 자율적으로 구성: 진짜로 배포할 코드를 push하는 branch 이름으로 변경
on:
  push:
    branches:
      - main # main브랜치에 push되었을 때
  pull_request:
    branches:
      - main # main브랜치에 pr 날렸을 때


jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    # GitHub 리포지토리를 체크아웃
    - name: checkout
      uses: actions/checkout@master
	
		# Action Secret에 설정한 ENV_VARS 값을 .env 파일로 만듦
    - name: create env file
      run: |
        touch .env
        echo "${{ secrets.ENV_VARS }}" >> .env
  
	  # EC2에 접속해 원격디렉토리 생성
    - name: create remote directory
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ec2-52-78-78-153.ap-northeast-2.compute.amazonaws.com
        username: ubuntu
        key: -----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEA0twEepG5se5QhQVO5CG39j43UvUhQSiZt+ro5S1RlKMeEqr1
qt7sVgdX5tvbSO+txn7Q13YXUpfgnoA+kh/ExBvE8VwbvanGBpMdad/IehI1ok4g
+25kPhqiLV/ySYl/HCdTXsJwwD9tDhj8wqifE4dPYi+Bhx6qU7w7gtuIMCy9lfod
nDqq88kMrbaTOVSHVyLcf8niliZghpoHpHyYtfeLl2fSBHHbPn5LSjK+ZvANXdog
1LCvSIdWxsJVLNFp/r99a4Co3QvsU/mw59GrYBVMgpjuGL1/AXQvYOAq4mFKobnT
9Tpfb4giS7r8apCdeg7hRWuBwDVV0jhnfgNCSwIDAQABAoIBAQCT7HXX5tN219D1
ALxPnrgHr63wLLeflnQAanPoEtrgg25dekHOFYWG9K/d7O7xQ/ONBPpNrTK/ZnzV
tPIwYMkRKsoG6K8tZyTdB+filnN178BglJ7exJreVqDfZCf9HtBlV9FM8OtYcyZ2
dWEczl6KvKocH2em+wRSqgK10nzADdzn0Qrx9l3PC6KWozH2zvu9pzBlYEZCbPqQ
97N1cWhJbvIU5AQUF7MlbM9WNFcN1Vjiu8xGC4KkTe7Y16TYZcSgs8l/9NKayoKn
opLFRx0xr+zM9f8ekwE9ZdcNL2XwJxKQA8N/XnYlLTwNPUo7pJlCCvM2eESQ4nJJ
BVj6SKJBAoGBAPA6cPL7lNfYa2jfIlzAqbj4N4f6SvGQ6F0hF+PLIaeVZGlvWIJ2
i2Wu2Qe04/KoXEDcJ4jm42NrEkqGMbJFn4bGrt5eZknsbZfqDs/5KyXwCWm7h62d
XRBMqPkDbn/2aV0Il7rFwHBMlfhCixpB2wP6nR7ZKM1KpFdgtFbRUnX/AoGBAOCz
+BFxYNNjed9Ob3W2zVvdRuzt0QSEIgLfl/FDCIvcVgrtXDCjtMu6JEeeuxmY0r9/
wZDs0roda60FmIifD98shoUEHUCEkYPXmkiLcDUHj1i0nDWhzqNEXg1pTTZlA4oL
lB0tU8XeGuqAP5DyxZvG9c5aYO8eWlHP9ApDHCu1AoGANCKKxsEAwYNPdDgQzg5m
ByWfb5xLTXfEZgm7lI1OJX+Phi5LCC1P/WZf5YNFgTE2rEDbN6PcL4RaOOA8wtLH
V0mhQ9M64co00qZSRqJt0dLxSAgR3wTq4JGyjjBHd+/zV+R4gWlPZU/JsFJIvA8U
yB1IohxA9aTAW9I58SmGeuMCgYEAixRZktJOUAjeQi1WJ9IBwb5wS+3W1ajDNGwY
q6gF/itexlysFx78pKyOEBZbUDibGRSGRqGOvMvA/dLc2pM5S7VPfb1SLcDgIG6u
fABybyBCxXDkzv1b3QpP/JUUyXo0epk4D+ciVvJmToca0SiyzvyS4CponRh4ZvMD
5eYr5ZECgYAoAY/ckpDogSl19twWjIReAg1wXGkJqjd4oB1B/Okbgg9SOqykkV4Q
HFNaMYWhgVG/f5GmcstAw+OiWfBphS9w0jvdCkUcq3WLWA0X0ux7Ndi4ZHofISrG
P7gD/mJlhYWteZT0GP7o95YXu6sFkQoAR324xFojdWptrDZWkYDdKA==
-----END RSA PRIVATE KEY-----
        script: mkdir -p /home/ubuntu/srv/ubuntu

		# SSH 키를 통해 소스 코드를 EC2 인스턴스(서버)로 복사
    - name: copy source via ssh key
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        remote_path: /home/ubuntu/srv/ubuntu/
        remote_host: ec2-52-78-78-153.ap-northeast-2.compute.amazonaws.com
        remote_user: ubuntu
        remote_key: -----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEA0twEepG5se5QhQVO5CG39j43UvUhQSiZt+ro5S1RlKMeEqr1
qt7sVgdX5tvbSO+txn7Q13YXUpfgnoA+kh/ExBvE8VwbvanGBpMdad/IehI1ok4g
+25kPhqiLV/ySYl/HCdTXsJwwD9tDhj8wqifE4dPYi+Bhx6qU7w7gtuIMCy9lfod
nDqq88kMrbaTOVSHVyLcf8niliZghpoHpHyYtfeLl2fSBHHbPn5LSjK+ZvANXdog
1LCvSIdWxsJVLNFp/r99a4Co3QvsU/mw59GrYBVMgpjuGL1/AXQvYOAq4mFKobnT
9Tpfb4giS7r8apCdeg7hRWuBwDVV0jhnfgNCSwIDAQABAoIBAQCT7HXX5tN219D1
ALxPnrgHr63wLLeflnQAanPoEtrgg25dekHOFYWG9K/d7O7xQ/ONBPpNrTK/ZnzV
tPIwYMkRKsoG6K8tZyTdB+filnN178BglJ7exJreVqDfZCf9HtBlV9FM8OtYcyZ2
dWEczl6KvKocH2em+wRSqgK10nzADdzn0Qrx9l3PC6KWozH2zvu9pzBlYEZCbPqQ
97N1cWhJbvIU5AQUF7MlbM9WNFcN1Vjiu8xGC4KkTe7Y16TYZcSgs8l/9NKayoKn
opLFRx0xr+zM9f8ekwE9ZdcNL2XwJxKQA8N/XnYlLTwNPUo7pJlCCvM2eESQ4nJJ
BVj6SKJBAoGBAPA6cPL7lNfYa2jfIlzAqbj4N4f6SvGQ6F0hF+PLIaeVZGlvWIJ2
i2Wu2Qe04/KoXEDcJ4jm42NrEkqGMbJFn4bGrt5eZknsbZfqDs/5KyXwCWm7h62d
XRBMqPkDbn/2aV0Il7rFwHBMlfhCixpB2wP6nR7ZKM1KpFdgtFbRUnX/AoGBAOCz
+BFxYNNjed9Ob3W2zVvdRuzt0QSEIgLfl/FDCIvcVgrtXDCjtMu6JEeeuxmY0r9/
wZDs0roda60FmIifD98shoUEHUCEkYPXmkiLcDUHj1i0nDWhzqNEXg1pTTZlA4oL
lB0tU8XeGuqAP5DyxZvG9c5aYO8eWlHP9ApDHCu1AoGANCKKxsEAwYNPdDgQzg5m
ByWfb5xLTXfEZgm7lI1OJX+Phi5LCC1P/WZf5YNFgTE2rEDbN6PcL4RaOOA8wtLH
V0mhQ9M64co00qZSRqJt0dLxSAgR3wTq4JGyjjBHd+/zV+R4gWlPZU/JsFJIvA8U
yB1IohxA9aTAW9I58SmGeuMCgYEAixRZktJOUAjeQi1WJ9IBwb5wS+3W1ajDNGwY
q6gF/itexlysFx78pKyOEBZbUDibGRSGRqGOvMvA/dLc2pM5S7VPfb1SLcDgIG6u
fABybyBCxXDkzv1b3QpP/JUUyXo0epk4D+ciVvJmToca0SiyzvyS4CponRh4ZvMD
5eYr5ZECgYAoAY/ckpDogSl19twWjIReAg1wXGkJqjd4oB1B/Okbgg9SOqykkV4Q
HFNaMYWhgVG/f5GmcstAw+OiWfBphS9w0jvdCkUcq3WLWA0X0ux7Ndi4ZHofISrG
P7gD/mJlhYWteZT0GP7o95YXu6sFkQoAR324xFojdWptrDZWkYDdKA==
-----END RSA PRIVATE KEY-----

		# 서버에 접속한 뒤 deploy.sh(배포 스크립트)를 실행
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ec2-52-78-78-153.ap-northeast-2.compute.amazonaws.com
        username: ubuntu
        key: -----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEA0twEepG5se5QhQVO5CG39j43UvUhQSiZt+ro5S1RlKMeEqr1
qt7sVgdX5tvbSO+txn7Q13YXUpfgnoA+kh/ExBvE8VwbvanGBpMdad/IehI1ok4g
+25kPhqiLV/ySYl/HCdTXsJwwD9tDhj8wqifE4dPYi+Bhx6qU7w7gtuIMCy9lfod
nDqq88kMrbaTOVSHVyLcf8niliZghpoHpHyYtfeLl2fSBHHbPn5LSjK+ZvANXdog
1LCvSIdWxsJVLNFp/r99a4Co3QvsU/mw59GrYBVMgpjuGL1/AXQvYOAq4mFKobnT
9Tpfb4giS7r8apCdeg7hRWuBwDVV0jhnfgNCSwIDAQABAoIBAQCT7HXX5tN219D1
ALxPnrgHr63wLLeflnQAanPoEtrgg25dekHOFYWG9K/d7O7xQ/ONBPpNrTK/ZnzV
tPIwYMkRKsoG6K8tZyTdB+filnN178BglJ7exJreVqDfZCf9HtBlV9FM8OtYcyZ2
dWEczl6KvKocH2em+wRSqgK10nzADdzn0Qrx9l3PC6KWozH2zvu9pzBlYEZCbPqQ
97N1cWhJbvIU5AQUF7MlbM9WNFcN1Vjiu8xGC4KkTe7Y16TYZcSgs8l/9NKayoKn
opLFRx0xr+zM9f8ekwE9ZdcNL2XwJxKQA8N/XnYlLTwNPUo7pJlCCvM2eESQ4nJJ
BVj6SKJBAoGBAPA6cPL7lNfYa2jfIlzAqbj4N4f6SvGQ6F0hF+PLIaeVZGlvWIJ2
i2Wu2Qe04/KoXEDcJ4jm42NrEkqGMbJFn4bGrt5eZknsbZfqDs/5KyXwCWm7h62d
XRBMqPkDbn/2aV0Il7rFwHBMlfhCixpB2wP6nR7ZKM1KpFdgtFbRUnX/AoGBAOCz
+BFxYNNjed9Ob3W2zVvdRuzt0QSEIgLfl/FDCIvcVgrtXDCjtMu6JEeeuxmY0r9/
wZDs0roda60FmIifD98shoUEHUCEkYPXmkiLcDUHj1i0nDWhzqNEXg1pTTZlA4oL
lB0tU8XeGuqAP5DyxZvG9c5aYO8eWlHP9ApDHCu1AoGANCKKxsEAwYNPdDgQzg5m
ByWfb5xLTXfEZgm7lI1OJX+Phi5LCC1P/WZf5YNFgTE2rEDbN6PcL4RaOOA8wtLH
V0mhQ9M64co00qZSRqJt0dLxSAgR3wTq4JGyjjBHd+/zV+R4gWlPZU/JsFJIvA8U
yB1IohxA9aTAW9I58SmGeuMCgYEAixRZktJOUAjeQi1WJ9IBwb5wS+3W1ajDNGwY
q6gF/itexlysFx78pKyOEBZbUDibGRSGRqGOvMvA/dLc2pM5S7VPfb1SLcDgIG6u
fABybyBCxXDkzv1b3QpP/JUUyXo0epk4D+ciVvJmToca0SiyzvyS4CponRh4ZvMD
5eYr5ZECgYAoAY/ckpDogSl19twWjIReAg1wXGkJqjd4oB1B/Okbgg9SOqykkV4Q
HFNaMYWhgVG/f5GmcstAw+OiWfBphS9w0jvdCkUcq3WLWA0X0ux7Ndi4ZHofISrG
P7gD/mJlhYWteZT0GP7o95YXu6sFkQoAR324xFojdWptrDZWkYDdKA==
-----END RSA PRIVATE KEY-----
        script: |
          sh /home/ubuntu/srv/ubuntu/config/scripts/deploy.sh
